apiVersion: v1
kind: Service
metadata:
  name: vehicle-sale-service
spec:
  selector:
    app: vehicle-sale-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
